# Unpack smartctl exporter tarball
- name: Unpack smartctl exporter tarball on amd64
  ansible.builtin.unarchive:
    src: /tmp/smartctl_exporter-{{ smartctl_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp
    remote_src: true
    owner: smartctl_exporter
    group: smartctl_exporter
    mode: '0755'
  when: ansible_architecture == "x86_64"

# Copy smartctl exporter binary to /usr/local/bin
- name: Copy smartctl exporter binary to /usr/local/bin on amd64
  ansible.builtin.copy:
    src: /tmp/smartctl_exporter-{{ smartctl_exporter_version }}.linux-amd64/smartctl_exporter
    dest: /usr/local/bin
    owner: smartctl_exporter
    group: smartctl_exporter
    mode: '0755'
    remote_src: true
  when: ansible_architecture == "x86_64"

# Remove smartctl_exporter tarball
- name: Remove smartctl_exporter tarball on amd64
  ansible.builtin.file:
    path: /tmp/smartctl_exporter-{{ smartctl_exporter_version }}.linux-arm64.tar.gz
    state: absent
  when: ansible_architecture == "x86_64"

# Remove smartctl_exporter directory
- name: Remove smartctl_exporter directory on amd64
  ansible.builtin.file:
    path: /tmp/smartctl_exporter-{{ smartctl_exporter_version }}.linux-arm64
    state: absent
  when: ansible_architecture == "x86_64"
