# Unpack node exporter tarball
- name: Unpack node exporter tarball on amd64
  ansible.builtin.unarchive:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp
    remote_src: true
    owner: node_exporter
    group: node_exporter
    mode: '0755'
  when: ansible_architecture == "x86_64"

# Copy node exporter binary to /usr/local/bin
- name: Copy node exporter binary to /usr/local/bin on amd64
  ansible.builtin.copy:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    dest: /usr/local/bin
    owner: node_exporter
    group: node_exporter
    mode: '0755'
    remote_src: true
  when: ansible_architecture == "x86_64"

# Remove node_exporter tarball
- name: Remove node_exporter tarball on amd64
  ansible.builtin.file:
    path: /tmp/node_exporter-{{ node_exporter_version }}.linux-arm64.tar.gz
    state: absent
  when: ansible_architecture == "x86_64"

# Remove node_exporter directory
- name: Remove node_exporter directory on amd64
  ansible.builtin.file:
    path: /tmp/node_exporter-{{ node_exporter_version }}.linux-arm64
    state: absent
  when: ansible_architecture == "x86_64"
