- name: Deploy Prometheus Exporters
  hosts: all
  gather_facts: true
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  roles:
    - role: node_exporter
    - role: smartctl_exporter
